LOCATIONS: dict = {
    'AD': 'Andorra',
    'AE': 'United Arab Emirates',
    'AF': 'Afghanistan',
    'AG': 'Antigua and Barbuda',
    'AI': 'Anguilla',
    'AL': 'Albania',
    'AM': 'Armenia',
    'AO': 'Angola',
    'AQ': 'Antarctica',
    'AR': 'Argentina',
    'AS': 'American Samoa',
    'AT': 'Austria',
    'AU': 'Australia',
    'AU-AC': 'Australia, Ashmore and Cartier Islands',
    'AU-ACT': 'Australia, Australian Capital Territory',
    'AU-IOT': 'Australia, Indian Ocean Territories',
    'AU-JBT': 'Australia, Jervis Bay Territory',
    'AU-NSW': 'Australia, New South Wales',
    'AU-NT': 'Australia, Northern Territory',
    'AU-QLD': 'Australia, Queensland',
    'AU-SA': 'Australia, South Australia',
    'AU-TAS': 'Australia, Tasmania',
    'AU-VIC': 'Australia, Victoria',
    'AU-WA': 'Australia, Western Australia',
    'AW': 'Aruba',
    'AX': 'Aland',
    'AZ': 'Azerbaijan',
    'Akrotiri': 'Akrotiri Sovereign Base Area',
    'Asia without China': 'Asia without China',
    'Australia, including overseas territories': 'Australia, including overseas territories',
    'BA': 'Bosnia and Herzegovina',
    'BALTSO': 'Baltic System Operator',
    'BB': 'Barbados',
    'BD': 'Bangladesh',
    'BE': 'Belgium',
    'BF': 'Burkina Faso',
    'BG': 'Bulgaria',
    'BH': 'Bahrain',
    'BI': 'Burundi',
    'BJ': 'Benin',
    'BL': 'Saint Barthelemy',
    'BM': 'Bermuda',
    'BN': 'Brunei',
    'BO': 'Bolivia',
    'BQ': 'Bonaire, Saint Eustatius and Saba',
    'BR': 'Brazil',
    'BR-AC': 'Brazil, Acre',
    'BR-AL': 'Brazil, Alagoas',
    'BR-AM': 'Brazil, Amazonas',
    'BR-AP': 'Brazil, Amapá',
    'BR-BA': 'Brazil, Bahia',
    'BR-CE': 'Brazil, Ceará',
    'BR-DF': 'Brazil, Distrito Federal',
    'BR-ES': 'Brazil, Espírito Santo',
    'BR-GO': 'Brazil, Goiás',
    'BR-MA': 'Brazil, Maranhão',
    'BR-MG': 'Brazil, Minas Gerais',
    'BR-MS': 'Brazil, Mato Grosso do Sul',
    'BR-MT': 'Brazil, Mato Grosso',
    'BR-Mid-western grid': 'Brazil, Mid-western grid',
    'BR-North-eastern grid': 'Brazil, North-eastern grid',
    'BR-Northern grid': 'Brazil, Northern grid',
    'BR-PA': 'Brazil, Pará',
    'BR-PB': 'Brazil, Paraíba',
    'BR-PE': 'Brazil, Pernambuco',
    'BR-PI': 'Brazil, Piauí',
    'BR-PR': 'Brazil, Paraná',
    'BR-RJ': 'Brazil, Rio de Janeiro',
    'BR-RN': 'Brazil, Rio Grande do Norte',
    'BR-RO': 'Brazil, Rondônia',
    'BR-RR': 'Brazil, Roraima',
    'BR-RS': 'Brazil, Rio Grande do Sul',
    'BR-SC': 'Brazil, Santa Catarina',
    'BR-SE': 'Brazil, Sergipe',
    'BR-SP': 'Brazil, São Paulo',
    'BR-South-eastern grid': 'Brazil, South-eastern grid',
    'BR-South-eastern/Mid-western grid': 'Brazil, South-eastern and Mid-western grid',
    'BR-Southern grid': 'Brazil, Southern grid',
    'BR-TO': 'Brazil, Tocantins',
    'BS': 'The Bahamas',
    'BT': 'Bhutan',
    'BV': 'Bouvet Island',
    'BW': 'Botswana',
    'BY': 'Belarus',
    'BZ': 'Belize',
    'Bajo Nuevo': 'Bajo Nuevo Bank (Petrel Is.)',
    'CA': 'Canada',
    'CA-AB': 'Canada, Alberta',
    'CA-BC': 'Canada, British Columbia',
    'CA-MB': 'Canada, Manitoba',
    'CA-NB': 'Canada, New Brunswick',
    'CA-NF': 'Canada, Newfoundland and Labrador',
    'CA-NS': 'Canada, Nova Scotia',
    'CA-NT': 'Canada, Northwest Territories',
    'CA-NU': 'Canada, Nunavut',
    'CA-ON': 'Canada, Ontario',
    'CA-PE': 'Canada, Prince Edward Island',
    'CA-QC': 'Canada, Québec',
    'CA-SK': 'Canada, Saskatchewan',
    'CA-YK': 'Canada, Yukon',
    'CC': 'Cocos (Keeling) Islands',
    'CD': 'Congo, Democratic Republic of the',
    'CENTREL': 'Central European Power Association',
    'CF': 'Central African Republic',
    'CG': 'Congo',
    'CH': 'Switzerland',
    'CI': 'Ivory Coast',
    'CK': 'Cook Islands',
    'CL': 'Chile',
    'CM': 'Cameroon',
    'CN': 'China',
    'CN-AH': 'China, Anhui (安徽)',
    'CN-BJ': 'China, Beijing (北京)',
    'CN-CCG': 'China, Central Grid',
    'CN-CQ': 'China, Chongqing (重庆)',
    'CN-CSG': 'China, China Southern Power Grid',
    'CN-ECGC': 'China, East Grid',
    'CN-FJ': 'China, Fujian (福建)',
    'CN-GD': 'China, Guangdong (广东)',
    'CN-GS': 'China, Gansu (甘肃)',
    'CN-GX': 'China, Guangxi (广西壮族自治区)',
    'CN-GZ': 'China, Guizhou (贵州)',
    'CN-HA': 'China, Hainan (海南)',
    'CN-HB': 'China, Hebei (河北)',
    'CN-HE': 'China, Henan (河南)',
    'CN-HL': 'China, Heilongjiang (黑龙江省)',
    'CN-HN': 'China, Hunan (湖南)',
    'CN-HU': 'China, Hubei (湖北)',
    'CN-JL': 'China, Jilin (吉林)',
    'CN-JS': 'China, Jiangsu (江苏)',
    'CN-JX': 'China, Jiangxi (江西)',
    'CN-LN': 'China, Liaoning (辽宁)',
    'CN-NCGC': 'China, North Grid',
    'CN-NECG': 'China, Northeast Grid',
    'CN-NM': 'China, Inner Mongol (内蒙古自治区)',
    'CN-NWG': 'China, Northwest Grid',
    'CN-NX': 'China, Ningxia (宁夏回族自治区)',
    'CN-QH': 'China, Qinghai (青海)',
    'CN-SA': 'China, Shaanxi (陕西)',
    'CN-SC': 'China, Sichuan (四川)',
    'CN-SD': 'China, Shandong (山东)',
    'CN-SGCC': 'China, State Grid Corporation of China',
    'CN-SH': 'China, Shanghai (上海)',
    'CN-SWG': 'China, Southwest Grid',
    'CN-SX': 'China, Shanxi (山西)',
    'CN-TJ': 'China, Tianjin (天津)',
    'CN-XJ': 'China, Xinjiang (新疆维吾尔自治区)',
    'CN-XZ': 'China, Xizang (西藏自治区)',
    'CN-YN': 'China, Yunnan (云南)',
    'CN-ZJ': 'China, Zhejiang (浙江)',
    'CO': 'Colombia',
    'CR': 'Costa Rica',
    'CS': 'Serbia and Montenegro',
    'CU': 'Cuba',
    'CUSMA/T-MEC/USMCA': 'United States–Mexico–Canada Agreement',
    'CV': 'Cape Verde',
    'CW': 'Curaçao',
    'CX': 'Christmas Island',
    'CY': 'Cyprus',
    'CZ': 'Czechia',
    'Canada without Alberta': 'Canada without Alberta',
    'Canada without Alberta and Quebec': 'Canada without Alberta and Quebec',
    'Canada without Quebec': 'Canada without Quebec',
    'Canary Islands': 'Canary Islands',
    'Central Asia': 'Central Asia',
    'China w/o Inner Mongol': 'China without Inner Mongol',
    'Clipperton Island': 'Clipperton Island',
    'Coral Sea Islands': 'Coral Sea Islands',
    'Crimea': 'Crimea',
    'Cyprus No Mans Area': 'Cyprus No Mans Area',
    'DE': 'Germany',
    'DJ': 'Djibouti',
    'DK': 'Denmark',
    'DM': 'Dominica',
    'DO': 'Dominican Republic',
    'DZ': 'Algeria',
    'Dhekelia Base': 'Dhekelia Sovereign Base Area',
    'EC': 'Ecuador',
    'EE': 'Estonia',
    'EG': 'Egypt',
    'EH': 'Western Sahara',
    'ENTSO-E': 'European Network of Transmission Systems Operators for Electricity',
    'ER': 'Eritrea',
    'ES': 'Spain',
    'ES-CN': 'Canary Islands',
    'ET': 'Ethiopia',
    'Europe without Austria': 'Europe without Austria',
    'Europe without NORDEL (NCPA)': 'Europe without NORDEL (NCPA)',
    'Europe without Switzerland': 'Europe without Switzerland',
    'Europe without Switzerland and Austria': 'Europe without Switzerland and Austria',
    'Europe without Switzerland and France': 'Europe without Switzerland and France',
    'Europe, without Russia and Türkiye': 'Europe, without Russia and Türkiye',
    'FI': 'Finland',
    'FJ': 'Fiji',
    'FK': 'Falkland Islands',
    'FM': 'Micronesia, Federated States of',
    'FO': 'Faroe Islands',
    'FR': 'France',
    'FSU': 'Commonwealth of Independent States',
    'France, including overseas territories': 'France, including overseas territories',
    'GA': 'Gabon',
    'GB': 'United Kingdom',
    'GD': 'Grenada',
    'GE': 'Georgia',
    'GF': 'French Guiana',
    'GG': 'Guernsey',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GL': 'Greenland',
    'GLO': 'Global',
    'GM': 'Gambia',
    'GN': 'Guinea',
    'GP': 'Guadeloupe',
    'GQ': 'Equatorial Guinea',
    'GR': 'Greece',
    'GS': 'South Georgia and South Sandwich Islands',
    'GT': 'Guatemala',
    'GU': 'Guam',
    'GW': 'Guinea Bissau',
    'GY': 'Guyana',
    'Guantanamo Bay': 'US Naval Base Guantanamo Bay',
    'HK': 'Hong Kong S.A.R.',
    'HM': 'Heard Island and McDonald Islands',
    'HN': 'Honduras',
    'HR': 'Croatia',
    'HT': 'Haiti',
    'HU': 'Hungary',
    'IAI Area, Africa': 'IAI Area, Africa',
    'IAI Area, Asia, without China and GCC': 'IAI Area, Asia, without China and GCC',
    'IAI Area, EU27 & EFTA': 'IAI Area, EU27 & EFTA',
    'IAI Area, Gulf Cooperation Council': 'IAI Area, Gulf Cooperation Council',
    'IAI Area, North America': 'IAI Area, North America',
    'IAI Area, North America, without Quebec': 'IAI Area, North America, without Quebec',
    'IAI Area, Russia & RER w/o EU27 & EFTA': 'IAI Area, Russia & Europe outside EU27 & EFTA',
    'IAI Area, South America': 'IAI Area, South America',
    'ID': 'Indonesia',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IM': 'Isle of Man',
    'IN': 'India',
    'IN-AN': 'India, Andaman and Nicobar',
    'IN-AP': 'India, Andhra Pradesh',
    'IN-AR': 'India, Arunachal Pradesh',
    'IN-AS': 'India, Assam',
    'IN-BR': 'India, Bihar',
    'IN-CH': 'India, Chandigarh',
    'IN-CT': 'India, Chhattisgarh',
    'IN-DD': 'India, Dadra and Nagar Haveli and Daman and Diu',
    'IN-DH': 'India, Dadra and Nagar Haveli and Daman and Diu',
    'IN-DL': 'India, Delhi',
    'IN-DN': 'India, Dadra and Nagar Haveli and Daman and Diu',
    'IN-Eastern grid': 'India, Eastern grid',
    'IN-GA': 'India, Goa',
    'IN-GJ': 'India, Gujarat',
    'IN-HP': 'India, Himachal Pradesh',
    'IN-HR': 'India, Haryana',
    'IN-Islands': 'India, Islands',
    'IN-JH': 'India, Jharkhand',
    'IN-JK': 'India, Jammu and Kashmir',
    'IN-KA': 'India, Karnataka',
    'IN-KL': 'India, Kerala',
    'IN-LA': 'India, Ladakh',
    'IN-LD': 'India, Lakshadweep',
    'IN-MH': 'India, Maharashtra',
    'IN-ML': 'India, Meghalaya',
    'IN-MN': 'India, Manipur',
    'IN-MP': 'India, Madhya Pradesh',
    'IN-MZ': 'India, Mizoram',
    'IN-NL': 'India, Nagaland',
    'IN-North-eastern grid': 'India, North-eastern grid',
    'IN-Northern grid': 'India, Northern grid',
    'IN-OR': 'India, Odisha',
    'IN-PB': 'India, Punjab',
    'IN-PY': 'India, Puducherry',
    'IN-RJ': 'India, Rajasthan',
    'IN-SK': 'India, Sikkim',
    'IN-Southern grid': 'India, Southern grid',
    'IN-TG': 'India, Telangana',
    'IN-TN': 'India, Tamil Nadu',
    'IN-TR': 'India, Tripura',
    'IN-UP': 'India, Uttar Pradesh',
    'IN-UT': 'India, Uttarakhand',
    'IN-WB': 'India, West Bengal',
    'IN-Western grid': 'India, Western grid',
    'IO': 'British Indian Ocean Territory',
    'IQ': 'Iraq',
    'IR': 'Iran',
    'IS': 'Iceland',
    'IT': 'Italy',
    'JE': 'Jersey',
    'JM': 'Jamaica',
    'JO': 'Jordan',
    'JP': 'Japan',
    'KE': 'Kenya',
    'KG': 'Kyrgyzstan',
    'KH': 'Cambodia',
    'KI': 'Kiribati',
    'KM': 'Comoros',
    'KN': 'Saint Kitts and Nevis',
    'KP': 'North Korea',
    'KR': 'South Korea',
    'KW': 'Kuwait',
    'KY': 'Cayman Islands',
    'KZ': 'Kazakhstan',
    'LA': 'Laos',
    'LB': 'Lebanon',
    'LC': 'Saint Lucia',
    'LI': 'Liechtenstein',
    'LK': 'Sri Lanka',
    'LR': 'Liberia',
    'LS': 'Lesotho',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'LV': 'Latvia',
    'LY': 'Libya',
    'MA': 'Morocco',
    'MC': 'Monaco',
    'MD': 'Moldova',
    'ME': 'Montenegro',
    'MF': 'Saint Martin',
    'MG': 'Madagascar',
    'MH': 'Marshall Islands',
    'MK': 'North Macedonia',
    'ML': 'Mali',
    'MM': 'Myanmar',
    'MN': 'Mongolia',
    'MO': 'Macao S.A.R.',
    'MP': 'Northern Mariana Islands',
    'MQ': 'Martinique',
    'MR': 'Mauritania',
    'MRO': 'Midwest Reliability Organization',
    'MS': 'Montserrat',
    'MT': 'Malta',
    'MU': 'Mauritius',
    'MV': 'Maldives',
    'MW': 'Malawi',
    'MX': 'Mexico',
    'MY': 'Malaysia',
    'MZ': 'Mozambique',
    'NA': 'Namibia',
    'NAFTA': 'North American Free Trade Agreement',
    'NC': 'New Caledonia',
    'NE': 'Niger',
    'NF': 'Norfolk Island',
    'NG': 'Nigeria',
    'NI': 'Nicaragua',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'NORDEL': 'Nordic Countries Power Association',
    'NP': 'Nepal',
    'NPCC': 'Northeast Power Coordinating Council',
    'NR': 'Nauru',
    'NU': 'Niue',
    'NZ': 'New Zealand',
    'North America without Quebec': 'North America without Quebec',
    'Northern Cyprus': 'Northern Cyprus',
    'OM': 'Oman',
    'OECD': 'Europe',
    'PA': 'Panama',
    'PE': 'Peru',
    'PF': 'French Polynesia',
    'PG': 'Papua New Guinea',
    'PH': 'Philippines',
    'PK': 'Pakistan',
    'PL': 'Poland',
    'PM': 'Saint Pierre and Miquelon',
    'PN': 'Pitcairn Islands',
    'PR': 'Puerto Rico',
    'PS': 'Palestine',
    'PT': 'Portugal',
    'PW': 'Palau',
    'PY': 'Paraguay',
    'QA': 'Qatar',
    'Québec, HQ distribution network': 'Québec, Hydro-Québec distribution network',
    'RAF': 'Africa',
    'RAS': 'Asia',
    'RE': 'Réunion',
    'RER': 'Europe',
    'RER w/o AT+BE+CH+DE+FR+IT': 'Europe without Austria, Belgium, France, Germany, Italy, Liechtenstein, Monaco, San Marino, Switzerland, and the Vatican',
    'RER w/o CH+DE': 'Europe without Germany and Switzerland',
    'RER w/o DE+NL+NO': 'Europe without Germany, the Netherlands, and Norway',
    'RER w/o DE+NL+NO+RU': 'Europe without Germany, the Netherlands, Norway, and Russia',
    'RER w/o DE+NL+RU': 'Europe without Germany, the Netherlands, and Russia',
    'RER w/o RU': 'Europe without Russia',
    'RLA': 'Latin America and the Caribbean',
    'RME': 'Middle East',
    'RNA': 'Northern America',
    'RO': 'Romania',
    'RS': 'Serbia',
    'RU': 'Russia',
    'RW': 'Rwanda',
    'RoE': 'Rest of Europe',
    'RoW': 'Rest of World',
    'Russia (Asia)': 'Russia (Asia)',
    'Russia (Europe)': 'Russia (Europe)',
    'SA': 'Saudi Arabia',
    'SAS': 'Southern Asia',
    'SB': 'Solomon Islands',
    'SC': 'Seychelles',
    'SD': 'Sudan',
    'SE': 'Sweden',
    'SG': 'Singapore',
    'SH': 'Saint Helena',
    'SI': 'Slovenia',
    'SJ': 'Svalbard and Jan Mayen',
    'SK': 'Slovakia',
    'SL': 'Sierra Leone',
    'SM': 'San Marino',
    'SN': 'Senegal',
    'SO': 'Somalia',
    'SR': 'Suriname',
    'SS': 'South Sudan',
    'ST': 'Sao Tome and Principe',
    'SV': 'El Salvador',
    'SX': 'Sint Maarten',
    'SY': 'Syria',
    'SZ': 'Eswatini',
    'Scarborough Reef': 'Scarborough Reef',
    'Serranilla Bank': 'Serranilla Bank',
    'Siachen Glacier': 'Siachen Glacier',
    'Somaliland': 'Somaliland',
    'Spratly Islands': 'Spratly Islands',
    'TC': 'Turks and Caicos Islands',
    'TD': 'Chad',
    'TF': 'French Southern and Antarctic Lands',
    'TG': 'Togo',
    'TH': 'Thailand',
    'TJ': 'Tajikistan',
    'TK': 'Tokelau',
    'TL': 'East Timor',
    'TM': 'Turkmenistan',
    'TN': 'Tunisia',
    'TO': 'Tonga',
    'TR': 'Türkiye',
    'TT': 'Trinidad and Tobago',
    'TV': 'Tuvalu',
    'TW': 'Taiwan',
    'TZ': 'Tanzania',
    'UA': 'Ukraine',
    'UCTE': 'Union for the Co-ordination of Transmission of Electricity',
    'UCTE without France': 'UCTE without France',
    'UCTE without Germany': 'UCTE without Germany',
    'UCTE without Germany and France': 'UCTE without Germany and France',
    'UG': 'Uganda',
    'UM': 'United States Minor Outlying Islands',
    'UN-AMERICAS': 'Americas',
    'UN-ASIA': 'Asia, UN Region',
    'UN-AUSTRALIANZ': 'Australia and New Zealand',
    'UN-CAMERICA': 'Central America',
    'UN-CARIBBEAN': 'Caribbean',
    'UN-EAFRICA': 'Eastern Africa',
    'UN-EASIA': 'Eastern Asia',
    'UN-EEUROPE': 'Eastern Europe',
    'UN-EUROPE': 'Europe, UN Region',
    'UN-MAFRICA': 'Middle Africa',
    'UN-MELANESIA': 'Melanesia',
    'UN-MICRONESIA': 'Micronesia',
    'UN-NAFRICA': 'Northern Africa',
    'UN-NEUROPE': 'Northern Europe',
    'UN-OCEANIA': 'Oceania',
    'UN-POLYNESIA': 'Polynesia',
    'UN-SAMERICA': 'South America',
    'UN-SASIA': 'Southern Africa',
    'UN-SEASIA': 'South-Eastern Asia',
    'UN-SEUROPE': 'Southern Europe',
    'UN-WAFRICA': 'Western Africa',
    'UN-WASIA': 'Western Asia',
    'US': 'United States of America',
    'US-AK': 'United States of America, Alaska',
    'US-AL': 'United States of America, Alabama',
    'US-AR': 'United States of America, Arkansas',
    'US-ASCC': 'Alaska Systems Coordinating Council',
    'US-AZ': 'United States of America, Arizona',
    'US-CA': 'United States of America, California',
    'US-CO': 'United States of America, Colorado',
    'US-CT': 'United States of America, Connecticut',
    'US-DC': 'United States of America, District of Columbia',
    'US-DE': 'United States of America, Delaware',
    'US-FL': 'United States of America, Florida',
    'US-FRCC': 'Florida Reliability Coordinating Council',
    'US-GA': 'United States of America, Georgia',
    'US-HI': 'United States of America, Hawaii',
    'US-HICC': 'HICC',
    'US-IA': 'United States of America, Iowa',
    'US-ID': 'United States of America, Idaho',
    'US-IL': 'United States of America, Illinois',
    'US-IN': 'United States of America, Indiana',
    'US-KS': 'United States of America, Kansas',
    'US-KY': 'United States of America, Kentucky',
    'US-LA': 'United States of America, Louisiana',
    'US-MA': 'United States of America, Massachusetts',
    'US-MD': 'United States of America, Maryland',
    'US-ME': 'United States of America, Maine',
    'US-MI': 'United States of America, Michigan',
    'US-MN': 'United States of America, Minnesota',
    'US-MO': 'United States of America, Missouri',
    'US-MRO': 'Midwest Reliability Organization, US part only',
    'US-MS': 'United States of America, Mississippi',
    'US-MT': 'United States of America, Montana',
    'US-NC': 'United States of America, North Carolina',
    'US-ND': 'United States of America, North Dakota',
    'US-NE': 'United States of America, Nebraska',
    'US-NH': 'United States of America, New Hampshire',
    'US-NJ': 'United States of America, New Jersey',
    'US-NM': 'United States of America, New Mexico',
    'US-NPCC': 'Northeast Power Coordinating Council, US part only',
    'US-NV': 'United States of America, Nevada',
    'US-NY': 'United States of America, New York',
    'US-OH': 'United States of America, Ohio',
    'US-OK': 'United States of America, Oklahoma',
    'US-OR': 'United States of America, Oregon',
    'US-PA': 'United States of America, Pennsylvania',
    'US-RFC': 'ReliabilityFirst Corporation',
    'US-RI': 'United States of America, Rhode Island',
    'US-SC': 'United States of America, South Carolina',
    'US-SD': 'United States of America, South Dakota',
    'US-SERC': 'SERC Reliability Corporation',
    'US-TN': 'United States of America, Tennessee',
    'US-TRE': 'Texas Regional Entity',
    'US-TX': 'United States of America, Texas',
    'US-UT': 'United States of America, Utah',
    'US-VA': 'United States of America, Virginia',
    'US-VT': 'United States of America, Vermont',
    'US-WA': 'United States of America, Washington',
    'US-WECC': 'Western Electricity Coordinating Council, US part only',
    'US-WI': 'United States of America, Wisconsin',
    'US-WV': 'United States of America, West Virginia',
    'US-WY': 'United States of America, Wyoming',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'United States of America, including overseas territories': 'United States of America, including overseas territories',
    'VA': 'Vatican',
    'VC': 'Saint Vincent and the Grenadines',
    'VE': 'Venezuela',
    'VG': 'British Virgin Islands',
    'VI': 'United States Virgin Islands',
    'VN': 'Vietnam',
    'VU': 'Vanuatu',
    'WECC': 'Western Electricity Coordinating Council',
    'WEU': 'Western Europe',
    'WF': 'Wallis and Futuna',
    'WS': 'Samoa',
    'XK': 'Kosovo',
    'YE': 'Yemen',
    'YT': 'Mayotte',
    'ZA': 'South Africa',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe',
    }